export default [
    {
        id: '1',
        gender: 'man',
        category: 't-shirt',
        image: '../../img/product/t-short/your-product%20(3).png',
        name: 'Light T-shirt',
        description: 'New Season T-shirt',
        price: 89.99,
        rating: '4',
        color: '',
        size: '',
        details: ['- Lorem Ipsum is simply dummy text of the printing',
            '- And typesetting industry.',
            '- Lorem Ipsum has been the industry\'s standummy',
            '- And typesetting industry.']
    },
    {
        id: '2',
        gender: 'man',
        category: 't-shirt',
        image: '../../img/product/t-short/your-product%20(3).png',
        name: 'Light T-shirt',
        description: 'New Season T-shirt',
        price: 89.99,
        rating: '4',
        color: '',
        size: '',
        details: ['- Lorem Ipsum is simply dummy text of the printing',
            '- And typesetting industry.',
            '- Lorem Ipsum has been the industry\'s standummy',
            '- And typesetting industry.']
    },
    {
        id: '3',
        gender: 'man',
        category: 't-shirt',
        image: '../../img/product/t-short/your-product%20(3).png',
        name: 'Light T-shirt',
        description: 'New Season T-shirt',
        price: 89.99,
        rating: '4',
        color: '',
        size: '',
        details: ['- Lorem Ipsum is simply dummy text of the printing',
            '- And typesetting industry.',
            '- Lorem Ipsum has been the industry\'s standummy',
            '- And typesetting industry.']
    },
    {
        id: '4',
        gender: 'man',
        category: 't-shirt',
        image: '../../img/product/t-short/your-product%20(3).png',
        name: 'Light T-shirt',
        description: 'New Season T-shirt',
        price: 89.99,
        rating: '4',
        color: '',
        size: '',
        details: ['- Lorem Ipsum is simply dummy text of the printing',
            '- And typesetting industry.',
            '- Lorem Ipsum has been the industry\'s standummy',
            '- And typesetting industry.']
    },
    {
        id: '5',
        gender: 'woman',
        category: 't-shirt',
        image: '../../img/product/t-short/your-product%20(3).png',
        name: 'Light T-shirt',
        description: 'New Season T-shirt',
        price: 89.99,
        rating: '4',
        color: '',
        size: '',
        details: ['- Lorem Ipsum is simply dummy text of the printing',
            '- And typesetting industry.',
            '- Lorem Ipsum has been the industry\'s standummy',
            '- And typesetting industry.']
    },
    {
        id: '6',
        gender: 'woman',
        category: 't-shirt',
        image: '../../img/product/t-short/your-product%20(3).png',
        name: 'Light T-shirt',
        description: 'New Season T-shirt',
        price: 89.99,
        rating: '4',
        color: '',
        size: '',
        details: ['- Lorem Ipsum is simply dummy text of the printing',
            '- And typesetting industry.',
            '- Lorem Ipsum has been the industry\'s standummy',
            '- And typesetting industry.']
    },
    {
        id: '7',
        gender: 'woman',
        category: 't-shirt',
        image: '../../img/product/t-short/your-product%20(3).png',
        name: 'Light T-shirt',
        description: 'New Season T-shirt',
        price: 89.99,
        rating: '4',
        color: '',
        size: '',
        details: ['- Lorem Ipsum is simply dummy text of the printing',
            '- And typesetting industry.',
            '- Lorem Ipsum has been the industry\'s standummy',
            '- And typesetting industry.']
    },
    {
        id: '8',
        gender: 'woman',
        category: 't-shirt',
        image: '../../img/product/t-short/your-product%20(3).png',
        name: 'Light T-shirt',
        description: 'New Season T-shirt',
        price: 89.99,
        rating: '4',
        color: '',
        size: '',
        details: ['- Lorem Ipsum is simply dummy text of the printing',
            '- And typesetting industry.',
            '- Lorem Ipsum has been the industry\'s standummy',
            '- And typesetting industry.']
    }

]
