export const FETCH_CLOTHES_START = 'FETCH_CLOTHES_START';
export const FETCH_CLOTHES_SUCCESS = 'FETCH_CLOTHES_SUCCESS';
export const FETCH_CLOTHES_FAILURE = 'FETCH_CLOTHES_FAILURE';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';


export const FETCH_CLOTHES_IN_CATEGORIES_START = 'FETCH_CLOTHES_IN_CATEGORIES_START';
export const FETCH_CLOTHES_IN_CATEGORIES_SUCCESS = 'FETCH_CLOTHES_IN_CATEGORIES_SUCCESS';
export const FETCH_CLOTHES_IN_CATEGORIES_FAILURE = 'FETCH_CLOTHES_IN_CATEGORIES_FAILURE';
