export const FETCH_CLOTHES_START = 'FETCH_CLOTHES_START';
export const FETCH_CLOTHES_SUCCESS = 'FETCH_CLOTHES_SUCCESS';
export const FETCH_CLOTHES_FAILURE = 'FETCH_CLOTHES_FAILURE';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';


export const FETCH_CLOTHES_IN_CATEGORIES_START = 'FETCH_CLOTHES_IN_CATEGORIES_START';
export const FETCH_CLOTHES_IN_CATEGORIES_SUCCESS = 'FETCH_CLOTHES_IN_CATEGORIES_SUCCESS';
export const FETCH_CLOTHES_IN_CATEGORIES_FAILURE = 'FETCH_CLOTHES_IN_CATEGORIES_FAILURE';

export const FETCH_CLOTHE_BY_ID_START = 'FETCH_CLOTHE_BY_ID_START';
export const FETCH_CLOTHE_BY_ID_SUCCESS = 'FETCH_CLOTHE_BY_ID_SUCCESS';
export const FETCH_CLOTHE_BY_ID_FAILURE = 'FETCH_CLOTHE_BY_ID_FAILURE';

export const ADD_CLOTHE_TO_BASKET = 'ADD_CLOTHE_TO_BASKET'; 
export const REMOVE_CLOTHE_FROM_BASKET = 'REMOVE_CLOTHE_FROM_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
